### PR TITLE
Version 0.4

### LINKED ISSUE #23: PHP 8 support
Since PHP 8 is released a few days ago, it would be a good idea to support it. The latest released version of this package requires [PHP ^5.3 | ^7.0](https://github.com/Dhii/output-renderer-interface/blob/407014d7fd1af0427958f2acd61aff008ee9e032/composer.json#L15).

### PR DESCRIPTION
**Pull request by XedinUnknown**
- Dropped support for PHP 5.x.
- Declared support for PHP 8.0 (fixes #23).
- Dropped some useless and obsolete dependencies.
- Removed some generic factory interfaces.
- Renderers can now throw generic exception.
- Added more specific factory interfaces.
- Context can no longer be an object e.g. `stdClass`.

### CODE REVIEW

**Review by mecha — COMMENTED** [review]
The interfaces look good. But I'm not sure the factory interfaces are necessary. We should have a discussion about factories before moving forward.

**Comment by XedinUnknown** [comment]
Fair enough. The reasoning is that things such as templates often need to be created in a de-coupled way, and that this seems to be necessary in most places where templates are used. I distinguished 2 common ways of creating a template:

1. From a template string, such as `'Hello, {$name}!'`. The consumer knows that the new template will produce a value based on that string.
2. From a path. This can be a pseudo filesystem path, or a config path, or whatever. The consumer knows that the new template will be based on something that corresponds to the path.

**Comment by mecha** [comment]
So in both of those cases, since the consumer knows what kind of template it wants to create, can't it just create it? Without a factory?

**Comment by XedinUnknown** [comment]
I really don't want to keep having these discussions about factories. I've explained it many times before, and the reasons are the same yet again: factories allow the consumer to be de-coupled from the exact type of the product.

I know you have an opinion about this, and that you described it in your Notion document. I'll read it soon.

**Pull request merged**
